### ISSUE TITLE
Add optional ServiceAccount to Pod specs

### ISSUE THREAD

**Issue by yannick-roeder** [bakdata/streams-bootstrap#154]
Allowing a name for an already existing ServiceAccount to be set in the Helm chart enables a Streams app Pod to be granted RBAC permissions

**Comment by philipp94831** [comment]
Isn't this fixed by #156?

**Comment by yannick-roeder** [comment]
Yes, fixed by https://github.com/bakdata/streams-bootstrap/pull/156
