### ISSUE TITLE
Support new KafkaStreams close options

### ISSUE THREAD

**Issue by philipp94831** [bakdata/streams-bootstrap#163]
https://kafka.apache.org/33/javadoc/org/apache/kafka/streams/KafkaStreams.html#close-org.apache.kafka.streams.KafkaStreams.CloseOptions-

Kafka Streams recently introduced new close options. This allows to specify if a leave consumer group request should be send on close. By default this is not the case. However, this leaves group members longer in the group than necessary. Depending on the configuration of the app, we should send a leave group request in the following cases:
- If no static group membership is configured: Leave group (member id will change no matter how Kafka Streams is configured)
- If static group membership is configured: Depends on the reasons for closing Kafka Streams (assuming we run on Kubernetes).
  - If the reason is an app crash: Do not leave group (pod will restart soon with the same member id)
  - If the pod is relocated, this depends on the deployment mode:
    - If deployed as StatefulSet: Do not leave group (pod will restart soon with the same member id)
    - If deployed as Deployment: Leave group (member id will change in new pod)
  - If the pod is scaled down: Leave group (no new member will join group)

I don't know if it is possible to determine the reason of a Shutdown event. There are [PreStop hooks for Kubernetes](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) which we can use but they require an HTTP endpoint and it does not seem to send details on the reason.

For now we could also use the Kafka Streams StateListener to distinguish shut down and error. In that case this would be the behavior:
- If no static group membership is configured: Leave group
- If static group membership is configured:
  - If the reason is an app crash (transition to `ERROR`): Do not leave group
  - If the pod is relocated or scaled down (transition to `NOT_RUNNING`):
    - If deployed as StatefulSet: Do not leave group (stick with the current behavior and static group membership can still leverage its advantage)
    - If deployed as Deployment: Leave group (member id will change in new pod if at all)

Question then would be how we determine if running as StatefulSet or Deployment. We could also stick with the old behavior (do not leave group) if static group membership is enabled.

**Comment by torbsto** [comment]
> I don't know if it is possible to determine the reason of a Shutdown event. There are [PreStop hooks for Kubernetes](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) which we can use but they require an HTTP endpoint and it does not seem to send details on the reason

It looks to me like they also support calling a script. Still, getting the reason why the pod is stopped seems pretty hard. Maybe we could query the API and check for the number of pods. If it is x/y where x > y, this could indicate scaling down, while x = y could indicate a relocation. Not sure how robust this is though.

> Question then would be how we determine if running as StatefulSet or Deployment. 

This seems pretty simple to implement. We can just add an env variable that we set through Helm.
