### ISSUE TITLE
CloseOptions supports timeout

### ISSUE THREAD

**Issue by robvadai** [bakdata/streams-bootstrap#189]
Change this line: https://github.com/bakdata/streams-bootstrap/blob/master/src/main/java/com/bakdata/kafka/KafkaStreamsApplication.java#L355

to include an optional timeout value in case the default `Long.MAX_VALUE` is not satisfactory for someone.

**Comment by philipp94831** [comment]
Hi @robvadai, feel free to submit a PR for this. Otherwise we will have a look once we have capacity on our end

**Comment by philipp94831** [comment]
Fixed by #207
